// source: scouting_data.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

// var jspb = require('google-protobuf');
var jspb = window.jspb;
var goog = jspb;
var global = globalThis;

goog.exportSymbol('proto.AutoClimb', null, global);
goog.exportSymbol('proto.DataSet', null, global);
goog.exportSymbol('proto.EndgameClimb', null, global);
goog.exportSymbol('proto.MatchData', null, global);
goog.exportSymbol('proto.MatchLevel', null, global);
goog.exportSymbol('proto.MatchSlot', null, global);
goog.exportSymbol('proto.SkillRating', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.MatchData = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.MatchData, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.MatchData.displayName = 'proto.MatchData';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.DataSet = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.DataSet.repeatedFields_, null);
};
goog.inherits(proto.DataSet, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.DataSet.displayName = 'proto.DataSet';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.MatchData.prototype.toObject = function(opt_includeInstance) {
  return proto.MatchData.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.MatchData} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.MatchData.toObject = function(includeInstance, msg) {
  var f, obj = {
matchNumber: jspb.Message.getFieldWithDefault(msg, 1, 0),
matchSlot: jspb.Message.getFieldWithDefault(msg, 2, 0),
teamNumber: jspb.Message.getFieldWithDefault(msg, 3, 0),
autoFuel: jspb.Message.getFieldWithDefault(msg, 4, 0),
autoNeutralZonePass: jspb.Message.getFieldWithDefault(msg, 5, 0),
autoClimb: jspb.Message.getFieldWithDefault(msg, 6, 0),
autoDepotPickup: jspb.Message.getBooleanFieldWithDefault(msg, 7, false),
autoOutpostPickup: jspb.Message.getBooleanFieldWithDefault(msg, 8, false),
autoNeutralZonePickup: jspb.Message.getBooleanFieldWithDefault(msg, 9, false),
teleopFuel: jspb.Message.getFieldWithDefault(msg, 10, 0),
teleopNeutralZonePass: jspb.Message.getFieldWithDefault(msg, 11, 0),
teleopOpponentZonePass: jspb.Message.getFieldWithDefault(msg, 12, 0),
teleopDepotPickup: jspb.Message.getBooleanFieldWithDefault(msg, 13, false),
teleopOutpostPickup: jspb.Message.getBooleanFieldWithDefault(msg, 14, false),
teleopNeutralZonePickup: jspb.Message.getBooleanFieldWithDefault(msg, 15, false),
teleopFloorPickup: jspb.Message.getBooleanFieldWithDefault(msg, 16, false),
endgameClimb: jspb.Message.getFieldWithDefault(msg, 17, 0),
driverSkill: jspb.Message.getFieldWithDefault(msg, 18, 0),
defensiveSkill: jspb.Message.getFieldWithDefault(msg, 19, 0),
robotSpeed: jspb.Message.getFieldWithDefault(msg, 20, 0),
crossedBump: jspb.Message.getBooleanFieldWithDefault(msg, 21, false),
crosssedTrench: jspb.Message.getBooleanFieldWithDefault(msg, 22, false),
immobilized: jspb.Message.getBooleanFieldWithDefault(msg, 23, false),
tippy: jspb.Message.getBooleanFieldWithDefault(msg, 24, false),
goodPartner: jspb.Message.getBooleanFieldWithDefault(msg, 25, false),
wasDefended: jspb.Message.getBooleanFieldWithDefault(msg, 26, false),
excessivePenalties: jspb.Message.getBooleanFieldWithDefault(msg, 27, false),
fuelPercentage: jspb.Message.getFieldWithDefault(msg, 28, 0),
notes: jspb.Message.getFieldWithDefault(msg, 29, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.binary.bytesource.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.MatchData}
 */
proto.MatchData.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.MatchData;
  return proto.MatchData.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.MatchData} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.MatchData}
 */
proto.MatchData.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setMatchNumber(value);
      break;
    case 2:
      var value = /** @type {!proto.MatchSlot} */ (reader.readEnum());
      msg.setMatchSlot(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setTeamNumber(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setAutoFuel(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setAutoNeutralZonePass(value);
      break;
    case 6:
      var value = /** @type {!proto.AutoClimb} */ (reader.readEnum());
      msg.setAutoClimb(value);
      break;
    case 7:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setAutoDepotPickup(value);
      break;
    case 8:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setAutoOutpostPickup(value);
      break;
    case 9:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setAutoNeutralZonePickup(value);
      break;
    case 10:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setTeleopFuel(value);
      break;
    case 11:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setTeleopNeutralZonePass(value);
      break;
    case 12:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setTeleopOpponentZonePass(value);
      break;
    case 13:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setTeleopDepotPickup(value);
      break;
    case 14:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setTeleopOutpostPickup(value);
      break;
    case 15:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setTeleopNeutralZonePickup(value);
      break;
    case 16:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setTeleopFloorPickup(value);
      break;
    case 17:
      var value = /** @type {!proto.EndgameClimb} */ (reader.readEnum());
      msg.setEndgameClimb(value);
      break;
    case 18:
      var value = /** @type {!proto.SkillRating} */ (reader.readEnum());
      msg.setDriverSkill(value);
      break;
    case 19:
      var value = /** @type {!proto.SkillRating} */ (reader.readEnum());
      msg.setDefensiveSkill(value);
      break;
    case 20:
      var value = /** @type {!proto.SkillRating} */ (reader.readEnum());
      msg.setRobotSpeed(value);
      break;
    case 21:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setCrossedBump(value);
      break;
    case 22:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setCrosssedTrench(value);
      break;
    case 23:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setImmobilized(value);
      break;
    case 24:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setTippy(value);
      break;
    case 25:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setGoodPartner(value);
      break;
    case 26:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setWasDefended(value);
      break;
    case 27:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setExcessivePenalties(value);
      break;
    case 28:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setFuelPercentage(value);
      break;
    case 29:
      var value = /** @type {string} */ (reader.readStringRequireUtf8());
      msg.setNotes(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.MatchData.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.MatchData.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.MatchData} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.MatchData.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMatchNumber();
  if (f !== 0) {
    writer.writeUint32(
      1,
      f
    );
  }
  f = message.getMatchSlot();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = message.getTeamNumber();
  if (f !== 0) {
    writer.writeUint32(
      3,
      f
    );
  }
  f = message.getAutoFuel();
  if (f !== 0) {
    writer.writeUint32(
      4,
      f
    );
  }
  f = message.getAutoNeutralZonePass();
  if (f !== 0) {
    writer.writeUint32(
      5,
      f
    );
  }
  f = message.getAutoClimb();
  if (f !== 0.0) {
    writer.writeEnum(
      6,
      f
    );
  }
  f = message.getAutoDepotPickup();
  if (f) {
    writer.writeBool(
      7,
      f
    );
  }
  f = message.getAutoOutpostPickup();
  if (f) {
    writer.writeBool(
      8,
      f
    );
  }
  f = message.getAutoNeutralZonePickup();
  if (f) {
    writer.writeBool(
      9,
      f
    );
  }
  f = message.getTeleopFuel();
  if (f !== 0) {
    writer.writeUint32(
      10,
      f
    );
  }
  f = message.getTeleopNeutralZonePass();
  if (f !== 0) {
    writer.writeUint32(
      11,
      f
    );
  }
  f = message.getTeleopOpponentZonePass();
  if (f !== 0) {
    writer.writeUint32(
      12,
      f
    );
  }
  f = message.getTeleopDepotPickup();
  if (f) {
    writer.writeBool(
      13,
      f
    );
  }
  f = message.getTeleopOutpostPickup();
  if (f) {
    writer.writeBool(
      14,
      f
    );
  }
  f = message.getTeleopNeutralZonePickup();
  if (f) {
    writer.writeBool(
      15,
      f
    );
  }
  f = message.getTeleopFloorPickup();
  if (f) {
    writer.writeBool(
      16,
      f
    );
  }
  f = message.getEndgameClimb();
  if (f !== 0.0) {
    writer.writeEnum(
      17,
      f
    );
  }
  f = message.getDriverSkill();
  if (f !== 0.0) {
    writer.writeEnum(
      18,
      f
    );
  }
  f = message.getDefensiveSkill();
  if (f !== 0.0) {
    writer.writeEnum(
      19,
      f
    );
  }
  f = message.getRobotSpeed();
  if (f !== 0.0) {
    writer.writeEnum(
      20,
      f
    );
  }
  f = message.getCrossedBump();
  if (f) {
    writer.writeBool(
      21,
      f
    );
  }
  f = message.getCrosssedTrench();
  if (f) {
    writer.writeBool(
      22,
      f
    );
  }
  f = message.getImmobilized();
  if (f) {
    writer.writeBool(
      23,
      f
    );
  }
  f = message.getTippy();
  if (f) {
    writer.writeBool(
      24,
      f
    );
  }
  f = message.getGoodPartner();
  if (f) {
    writer.writeBool(
      25,
      f
    );
  }
  f = message.getWasDefended();
  if (f) {
    writer.writeBool(
      26,
      f
    );
  }
  f = message.getExcessivePenalties();
  if (f) {
    writer.writeBool(
      27,
      f
    );
  }
  f = message.getFuelPercentage();
  if (f !== 0) {
    writer.writeUint32(
      28,
      f
    );
  }
  f = message.getNotes();
  if (f.length > 0) {
    writer.writeString(
      29,
      f
    );
  }
};


/**
 * optional uint32 match_number = 1;
 * @return {number}
 */
proto.MatchData.prototype.getMatchNumber = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.MatchData} returns this
 */
proto.MatchData.prototype.setMatchNumber = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional MatchSlot match_slot = 2;
 * @return {!proto.MatchSlot}
 */
proto.MatchData.prototype.getMatchSlot = function() {
  return /** @type {!proto.MatchSlot} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {!proto.MatchSlot} value
 * @return {!proto.MatchData} returns this
 */
proto.MatchData.prototype.setMatchSlot = function(value) {
  return jspb.Message.setProto3EnumField(this, 2, value);
};


/**
 * optional uint32 team_number = 3;
 * @return {number}
 */
proto.MatchData.prototype.getTeamNumber = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.MatchData} returns this
 */
proto.MatchData.prototype.setTeamNumber = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional uint32 auto_fuel = 4;
 * @return {number}
 */
proto.MatchData.prototype.getAutoFuel = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.MatchData} returns this
 */
proto.MatchData.prototype.setAutoFuel = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional uint32 auto_neutral_zone_pass = 5;
 * @return {number}
 */
proto.MatchData.prototype.getAutoNeutralZonePass = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.MatchData} returns this
 */
proto.MatchData.prototype.setAutoNeutralZonePass = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional AutoClimb auto_climb = 6;
 * @return {!proto.AutoClimb}
 */
proto.MatchData.prototype.getAutoClimb = function() {
  return /** @type {!proto.AutoClimb} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {!proto.AutoClimb} value
 * @return {!proto.MatchData} returns this
 */
proto.MatchData.prototype.setAutoClimb = function(value) {
  return jspb.Message.setProto3EnumField(this, 6, value);
};


/**
 * optional bool auto_depot_pickup = 7;
 * @return {boolean}
 */
proto.MatchData.prototype.getAutoDepotPickup = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 7, false));
};


/**
 * @param {boolean} value
 * @return {!proto.MatchData} returns this
 */
proto.MatchData.prototype.setAutoDepotPickup = function(value) {
  return jspb.Message.setProto3BooleanField(this, 7, value);
};


/**
 * optional bool auto_outpost_pickup = 8;
 * @return {boolean}
 */
proto.MatchData.prototype.getAutoOutpostPickup = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 8, false));
};


/**
 * @param {boolean} value
 * @return {!proto.MatchData} returns this
 */
proto.MatchData.prototype.setAutoOutpostPickup = function(value) {
  return jspb.Message.setProto3BooleanField(this, 8, value);
};


/**
 * optional bool auto_neutral_zone_pickup = 9;
 * @return {boolean}
 */
proto.MatchData.prototype.getAutoNeutralZonePickup = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 9, false));
};


/**
 * @param {boolean} value
 * @return {!proto.MatchData} returns this
 */
proto.MatchData.prototype.setAutoNeutralZonePickup = function(value) {
  return jspb.Message.setProto3BooleanField(this, 9, value);
};


/**
 * optional uint32 teleop_fuel = 10;
 * @return {number}
 */
proto.MatchData.prototype.getTeleopFuel = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 10, 0));
};


/**
 * @param {number} value
 * @return {!proto.MatchData} returns this
 */
proto.MatchData.prototype.setTeleopFuel = function(value) {
  return jspb.Message.setProto3IntField(this, 10, value);
};


/**
 * optional uint32 teleop_neutral_zone_pass = 11;
 * @return {number}
 */
proto.MatchData.prototype.getTeleopNeutralZonePass = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 11, 0));
};


/**
 * @param {number} value
 * @return {!proto.MatchData} returns this
 */
proto.MatchData.prototype.setTeleopNeutralZonePass = function(value) {
  return jspb.Message.setProto3IntField(this, 11, value);
};


/**
 * optional uint32 teleop_opponent_zone_pass = 12;
 * @return {number}
 */
proto.MatchData.prototype.getTeleopOpponentZonePass = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 12, 0));
};


/**
 * @param {number} value
 * @return {!proto.MatchData} returns this
 */
proto.MatchData.prototype.setTeleopOpponentZonePass = function(value) {
  return jspb.Message.setProto3IntField(this, 12, value);
};


/**
 * optional bool teleop_depot_pickup = 13;
 * @return {boolean}
 */
proto.MatchData.prototype.getTeleopDepotPickup = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 13, false));
};


/**
 * @param {boolean} value
 * @return {!proto.MatchData} returns this
 */
proto.MatchData.prototype.setTeleopDepotPickup = function(value) {
  return jspb.Message.setProto3BooleanField(this, 13, value);
};


/**
 * optional bool teleop_outpost_pickup = 14;
 * @return {boolean}
 */
proto.MatchData.prototype.getTeleopOutpostPickup = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 14, false));
};


/**
 * @param {boolean} value
 * @return {!proto.MatchData} returns this
 */
proto.MatchData.prototype.setTeleopOutpostPickup = function(value) {
  return jspb.Message.setProto3BooleanField(this, 14, value);
};


/**
 * optional bool teleop_neutral_zone_pickup = 15;
 * @return {boolean}
 */
proto.MatchData.prototype.getTeleopNeutralZonePickup = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 15, false));
};


/**
 * @param {boolean} value
 * @return {!proto.MatchData} returns this
 */
proto.MatchData.prototype.setTeleopNeutralZonePickup = function(value) {
  return jspb.Message.setProto3BooleanField(this, 15, value);
};


/**
 * optional bool teleop_floor_pickup = 16;
 * @return {boolean}
 */
proto.MatchData.prototype.getTeleopFloorPickup = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 16, false));
};


/**
 * @param {boolean} value
 * @return {!proto.MatchData} returns this
 */
proto.MatchData.prototype.setTeleopFloorPickup = function(value) {
  return jspb.Message.setProto3BooleanField(this, 16, value);
};


/**
 * optional EndgameClimb endgame_climb = 17;
 * @return {!proto.EndgameClimb}
 */
proto.MatchData.prototype.getEndgameClimb = function() {
  return /** @type {!proto.EndgameClimb} */ (jspb.Message.getFieldWithDefault(this, 17, 0));
};


/**
 * @param {!proto.EndgameClimb} value
 * @return {!proto.MatchData} returns this
 */
proto.MatchData.prototype.setEndgameClimb = function(value) {
  return jspb.Message.setProto3EnumField(this, 17, value);
};


/**
 * optional SkillRating driver_skill = 18;
 * @return {!proto.SkillRating}
 */
proto.MatchData.prototype.getDriverSkill = function() {
  return /** @type {!proto.SkillRating} */ (jspb.Message.getFieldWithDefault(this, 18, 0));
};


/**
 * @param {!proto.SkillRating} value
 * @return {!proto.MatchData} returns this
 */
proto.MatchData.prototype.setDriverSkill = function(value) {
  return jspb.Message.setProto3EnumField(this, 18, value);
};


/**
 * optional SkillRating defensive_skill = 19;
 * @return {!proto.SkillRating}
 */
proto.MatchData.prototype.getDefensiveSkill = function() {
  return /** @type {!proto.SkillRating} */ (jspb.Message.getFieldWithDefault(this, 19, 0));
};


/**
 * @param {!proto.SkillRating} value
 * @return {!proto.MatchData} returns this
 */
proto.MatchData.prototype.setDefensiveSkill = function(value) {
  return jspb.Message.setProto3EnumField(this, 19, value);
};


/**
 * optional SkillRating robot_speed = 20;
 * @return {!proto.SkillRating}
 */
proto.MatchData.prototype.getRobotSpeed = function() {
  return /** @type {!proto.SkillRating} */ (jspb.Message.getFieldWithDefault(this, 20, 0));
};


/**
 * @param {!proto.SkillRating} value
 * @return {!proto.MatchData} returns this
 */
proto.MatchData.prototype.setRobotSpeed = function(value) {
  return jspb.Message.setProto3EnumField(this, 20, value);
};


/**
 * optional bool crossed_bump = 21;
 * @return {boolean}
 */
proto.MatchData.prototype.getCrossedBump = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 21, false));
};


/**
 * @param {boolean} value
 * @return {!proto.MatchData} returns this
 */
proto.MatchData.prototype.setCrossedBump = function(value) {
  return jspb.Message.setProto3BooleanField(this, 21, value);
};


/**
 * optional bool crosssed_trench = 22;
 * @return {boolean}
 */
proto.MatchData.prototype.getCrosssedTrench = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 22, false));
};


/**
 * @param {boolean} value
 * @return {!proto.MatchData} returns this
 */
proto.MatchData.prototype.setCrosssedTrench = function(value) {
  return jspb.Message.setProto3BooleanField(this, 22, value);
};


/**
 * optional bool immobilized = 23;
 * @return {boolean}
 */
proto.MatchData.prototype.getImmobilized = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 23, false));
};


/**
 * @param {boolean} value
 * @return {!proto.MatchData} returns this
 */
proto.MatchData.prototype.setImmobilized = function(value) {
  return jspb.Message.setProto3BooleanField(this, 23, value);
};


/**
 * optional bool tippy = 24;
 * @return {boolean}
 */
proto.MatchData.prototype.getTippy = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 24, false));
};


/**
 * @param {boolean} value
 * @return {!proto.MatchData} returns this
 */
proto.MatchData.prototype.setTippy = function(value) {
  return jspb.Message.setProto3BooleanField(this, 24, value);
};


/**
 * optional bool good_partner = 25;
 * @return {boolean}
 */
proto.MatchData.prototype.getGoodPartner = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 25, false));
};


/**
 * @param {boolean} value
 * @return {!proto.MatchData} returns this
 */
proto.MatchData.prototype.setGoodPartner = function(value) {
  return jspb.Message.setProto3BooleanField(this, 25, value);
};


/**
 * optional bool was_defended = 26;
 * @return {boolean}
 */
proto.MatchData.prototype.getWasDefended = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 26, false));
};


/**
 * @param {boolean} value
 * @return {!proto.MatchData} returns this
 */
proto.MatchData.prototype.setWasDefended = function(value) {
  return jspb.Message.setProto3BooleanField(this, 26, value);
};


/**
 * optional bool excessive_penalties = 27;
 * @return {boolean}
 */
proto.MatchData.prototype.getExcessivePenalties = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 27, false));
};


/**
 * @param {boolean} value
 * @return {!proto.MatchData} returns this
 */
proto.MatchData.prototype.setExcessivePenalties = function(value) {
  return jspb.Message.setProto3BooleanField(this, 27, value);
};


/**
 * optional uint32 fuel_percentage = 28;
 * @return {number}
 */
proto.MatchData.prototype.getFuelPercentage = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 28, 0));
};


/**
 * @param {number} value
 * @return {!proto.MatchData} returns this
 */
proto.MatchData.prototype.setFuelPercentage = function(value) {
  return jspb.Message.setProto3IntField(this, 28, value);
};


/**
 * optional string notes = 29;
 * @return {string}
 */
proto.MatchData.prototype.getNotes = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 29, ""));
};


/**
 * @param {string} value
 * @return {!proto.MatchData} returns this
 */
proto.MatchData.prototype.setNotes = function(value) {
  return jspb.Message.setProto3StringField(this, 29, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.DataSet.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.DataSet.prototype.toObject = function(opt_includeInstance) {
  return proto.DataSet.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.DataSet} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.DataSet.toObject = function(includeInstance, msg) {
  var f, obj = {
matchesList: jspb.Message.toObjectList(msg.getMatchesList(),
    proto.MatchData.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.binary.bytesource.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.DataSet}
 */
proto.DataSet.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.DataSet;
  return proto.DataSet.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.DataSet} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.DataSet}
 */
proto.DataSet.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.MatchData;
      reader.readMessage(value,proto.MatchData.deserializeBinaryFromReader);
      msg.addMatches(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.DataSet.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.DataSet.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.DataSet} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.DataSet.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMatchesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.MatchData.serializeBinaryToWriter
    );
  }
};


/**
 * repeated MatchData matches = 1;
 * @return {!Array<!proto.MatchData>}
 */
proto.DataSet.prototype.getMatchesList = function() {
  return /** @type{!Array<!proto.MatchData>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.MatchData, 1));
};


/**
 * @param {!Array<!proto.MatchData>} value
 * @return {!proto.DataSet} returns this
*/
proto.DataSet.prototype.setMatchesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.MatchData=} opt_value
 * @param {number=} opt_index
 * @return {!proto.MatchData}
 */
proto.DataSet.prototype.addMatches = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.MatchData, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.DataSet} returns this
 */
proto.DataSet.prototype.clearMatchesList = function() {
  return this.setMatchesList([]);
};


/**
 * @enum {number}
 */
proto.MatchSlot = {
  RED_1: 0,
  RED_2: 1,
  RED_3: 2,
  BLUE_1: 3,
  BLUE_2: 4,
  BLUE_3: 5
};

/**
 * @enum {number}
 */
proto.MatchLevel = {
  QUALIFICATION: 0,
  SEMI_FINAL: 1,
  FINAL: 2
};

/**
 * @enum {number}
 */
proto.AutoClimb = {
  CLIMBED: 0,
  AUTO_CLIMB_ATTEMPTED: 1,
  AUTO_CLIMB_NOT_ATTEMPTED: 2
};

/**
 * @enum {number}
 */
proto.EndgameClimb = {
  LEVEL_1: 0,
  LEVEL_2: 1,
  LEVEL_3: 2,
  ENDGAME_CLIMB_ATTEMPTED: 3,
  ENDGAME_CLIMB_NOT_ATTEMPTED: 4
};

/**
 * @enum {number}
 */
proto.SkillRating = {
  BELOW_AVERAGE: 0,
  AVERAGE: 1,
  ABOVE_AVERAGE: 2,
  NOT_RATED: 3
};

goog.object.extend(exports, proto);
